dc/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

dc/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:id>/', views.detail, name='detail'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/update/', views.update, name='update'),
    path('<int:id>/like', views.like, name='like'),
]

dc/dcinside/urls.py
from django.contrib import admin
from django.urls import path, include
from board import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    # path('', include('board.urls')),
    path('', views.index),
    path('accounts/', include('accounts.urls')),
]

dc/accounts/models.py
from django.db import models

# Create your models here.

dc/board/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class Poster(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateField(auto_now_add=True)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='like_posts')
    # user = models.ForeignKey(settings.AUTH_USER_MODEL,
    #                          on_delete=models.CASCADE)

dc/board/forms.py
from django import forms
from .models import Poster


class PosterForm(forms.ModelForm):
        # created_at = forms.DateField(
        #     widget=forms.DateInput(attrs={'type': 'date'}))
    content = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Poster
        fields = ('title', 'content',)

dc/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
# Create your views here.


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
    else:
        form = UserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST) 
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('board:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)


def logout(request):
    auth_logout(request)
    return redirect('accounts:login')

dc/board/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Poster
from .forms import PosterForm
from IPython import embed
from django.contrib.auth.decorators import login_required
# Create your views here.


def index(request):
    boards = Poster.objects.all()
    context = {
        'boards': boards,
    }
    return render(request, 'board/index.html', context)


@login_required
def create(request):
    if request.method == 'POST':
        posterform = PosterForm(request.POST)
        if posterform.is_valid():
            posterform.save()
            # poster = posterform.save(commit=False)
            # poster.user = request.user
            # poster.save()
            return redirect('board:index')
        else:
            form = PosterForm()  # 폼을 자동으로 불러온다
            context = {
                'form': form
            }
            return render(request, 'board/form.html', context)

    else:
        form = PosterForm()  # 폼을 자동으로 불러온다
        context = {
            'form': form
        }
        return render(request, 'board/form.html', context)


def detail(request, id):
    # DB(해당 모델)에서 같은 id를 가진 게시글 가져오기
    poster = Poster.objects.get(id=id)
    context = {
        'poster': poster,
    }
    return render(request, 'board/detail.html', context)


def delete(request, id):
    poster = Poster.objects.get(id=id)
    poster.delete()
    return redirect('board:index')


def update(request, id):
    poster = Poster.objects.get(id=id)
    if request.method == 'POST':
        posterform = PosterForm(request.POST, instance=poster)
        if posterform.is_valid():
            posterform.save()
            return redirect('board:detail', id)
    else:
        form = PosterForm(instance=poster)
        context = {
            'form': form,
        }
        return render(request, 'board/form.html', context)
 # 기존의 게시글 내용이 적힌 폼 보여주기
 # form.html의 action을 빈칸으로 두는 이유
 # redirect 변수 할당
 # 모델폼 매개변수 1. request.POST 2. instance


@login_required
def like(request, id):
    user = request.user
    post = get_object_or_404(Poster, id=id)
    if user in post.like_users.all():
        post.like_users.remove(user)
    else:
        post.like_users.add(user)
    return redirect('board:index')

dc/accounts/templates/accounts/form.html
{% extends 'base.html' %}

{% block body %}
<form action="" method='POST'>
  {% csrf_token %}
  <table>
    {{form.as_table}}
  </table>
  <input type="submit" value='제출'>
</form>
{% endblock %}

dc/board/templates/board/detail.html
{% extends 'base.html' %}
{% block body %}

{% comment %}
형식 기억 잘하기 {{poster.title}}}!!
get 방식일 경우 a 태그를 활용

{% endcomment %}

{{poster.title}}
{{poster.content}}
{{poster.created_at}}
<form action="{% url 'board:delete' poster.id %}" method='POST'>
  {% csrf_token %}
  <input type="submit" value='삭제'>
</form>


<a href="{% url 'board:update' poster.id %}">수정</a>


<a href="{% url 'board:index' %}">메인으로</a>

{% endblock %}

dc/board/templates/board/form.html
{% extends 'base.html' %}
{% block body %}
{% comment %}
- DTL 주석
DTL if문
{% if 조건식1 %}
{% elif 조건식2 %}
{% else %}
{% endif %}
이런 식으로 html 태그 내부에서도 활용 가능
{% endcomment %}

<form action="" method='post'>
  {% comment %}
  "{% url '앱이름:path설정이름' 변수이름1, 변수이름2, ...%}"
  form 가져오기
  {% endcomment %}

  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="제출">
</form>


{% endblock %}

dc/board/templates/board/index.html
{% extends 'base.html' %}
{% block body %}
{% if user.is_authenticated %}
{{user.username}}
<a href="{% url 'accounts:logout' %}">
  로그아웃
</a>
{% else %}
{% endif %}

{% for board in boards %}
<a href="{% url 'board:detail' board.id %}">

  {{board.title}}</a>
{{board.content}}
{% if user in board.like_users.all %}
<a href="{% url 'board:like' board.id %}">
  좋아요 취소
</a>
{% else %}
<a href="{% url 'board:like' board.id %}">
  좋아요
</a>
{% endif %}
{% endfor %}
{% endblock %}

dc/dcinside/templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>DCINSIDE</title>
</head>

<body>
  {% block body %}
  {% endblock %}
</body>

</html>