191024/PASS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
]

191024/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

191024/posts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:id>/',views.detail, name='detail'),
    path('<int:id>/delete', views.delete, name='delete'),
]

191024/accounts/models.py
from django.db import models

# Create your models here.

191024/posts/models.py
from django.db import models
from django.conf import settings
# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

191024/posts/forms.py
from .models import Post
from django import forms 

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content')

191024/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as Auth_login
from django.contrib.auth import logout as Auth_logout
# Create your views here.


def index(request):
    # pass
    return render(request, 'accounts/index.html')


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'accounts/index.html')
    else:
        form = UserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            Auth_login(request, form.get_user())
        return render(request, 'accounts/index.html')
    else:
        form = AuthenticationForm
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)


def logout(request):
    Auth_logout(request)
    return render(request, 'accounts/index.html')

191024/posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from .forms import PostForm

# Create your views here.


def index(request):
    posts = Post.objects.all()
    context = {
        'posts': posts
    }
    return render(request, 'posts/index.html', context)


def create(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
        return render(request, 'posts/index.html')
    else:
        form = PostForm()
    context = {
        'form':form
    }
    return render(request, 'posts/form.html', context)

def detail(request, id):
    #posts로 쓰지마 post로 써! 하나만 불러오니까!
    post = Post.objects.get(id=id)
    context = {
        'post':post
    }
    return render(request, 'posts/detail.html', context)

def delete(request, id):
    post = Post.objects.get(id=id)
    post.delete()
    return redirect('posts:index')

191024/PASS/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>

<body>

  <a href="{% url 'accounts:index' %}">홈</a>
  <a href="{% url 'accounts:signup' %}">횐가입</a>
  {% if user.is_authenticated %}
  <a href="{% url 'accounts:logout' %}">로가웃</a>
  {# 아이디 인자를 빼먹지 말자1 #}
  <a href="{% url 'posts:create' %}">글 등록</a>
  {# 글 삭제는 ㄴ여기에 있으면 안돼 모ㄴㅣ터 옆에 전원버튼 있는 니낌 #}
  {% else %}
  <a href="{% url 'accounts:login' %}">로그인</a>
  {% endif %}

  {% block body %}
  {% endblock %}

</body>

</html>

191024/accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% block body %}
<form action="" method="POST">
  {% csrf_token %}
  {{form}}
  <input type="submit">
</form>
{% endblock %}

191024/accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% block body %}
<h1>123123</h1>
{% endblock %}

191024/posts/templates/posts/detail.html
{% extends 'base.html' %}
{% block body %}

{{posts.title}}
{{posts.content}}


<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="삭제">
</form>
{% endblock %}

191024/posts/templates/posts/form.html
{% extends 'base.html' %}
{% block body %}
<form action="" method="POST">
  {% csrf_token %}
  {{form}}
  <input type="submit">
</form>
{% endblock %}

191024/posts/templates/posts/index.html
{% extends 'base.html' %}
{% block body %}
  {% for post in posts %}
    {% comment %}
    # 여기 뭐 나와야해?
    # posts:detail의 posts는 urls.py의 app_name!
    {% endcomment %}
    <a href="{% url 'posts:detail' post.id %}">
      {{post.title}}
      {{post.content}}
      <input type="submit" value="등록">
    </a>

    <a href="{% url 'posts:delete' post.id %}">
      <input type="submit" value="삭제">
    </a>

  {% endfor %}
{% endblock %}