insta-clone/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('<int:id>/', views.user_page, name="user_page"),
    path('<int:id>/follow/', views.follow, name="follow"),
]

insta-clone/insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

insta-clone/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('hashtags/<int:id>/', views.hashtags, name='hashtags'),
    path('<int:id>/like/', views.like, name='like'),
]

insta-clone/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
# Create your models here.


class User(AbstractUser):
    followers = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='followings')

insta-clone/posts/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.


class HashTag(models.Model):
    content = models.CharField(max_length=100)


class Post(models.Model):
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)

    image = ProcessedImageField(
        processors=[ResizeToFill(300, 300)],
        format='JPEG',
        options={'quality': 90},
        upload_to='media'
    )

    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='like_posts')
    created_at = models.DateTimeField(auto_now_add=True)
    hashtags = models.ManyToManyField(HashTag, related_name='tagged_post')

insta-clone/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User

insta-clone/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('content', 'image')

insta-clone/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .forms import CustomUserCreationForm
from .models import User


# Create your views here.


def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('posts:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)


def logout(request):
    auth_logout(request)
    return redirect("accounts:login")


def user_page(request, id):
    user_info = get_object_or_404(User, id=id)
    context = {
        'user_info': user_info
    }
    return render(request, 'accounts/user_page.html', context)


def follow(request, id):
    you = get_object_or_404(User, id=id)
    me = request.user

    if you != me:

        # if 내가 이미 팔로우 했닝ㅇ->했으면 팔로우 취소 아니면 팔로우

        # if me in you.followers.all():
        #     you.followers.remove(me)

        # else:
        #     you.followers.add(me)
        # return redirect('accounts:user_page', id)

        if me in you.followers.all():
            me.followings.remove(you)

        else:
            me.followings.add(you)

    return redirect('accounts:user_page', id)

insta-clone/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostForm
from .models import HashTag, Post
# Create your views here.


def index(request):
    posts = Post.objects.all()
    context = {
        'posts': posts
    }
    return render(request, 'posts/index.html', context)


def create(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            for word in post.content.split():
                if word.startswith('#'):
                    # hashtag 추가
                    hashtag = HashTag.objects.get_or_create(
                        content=word)[0]  # (obj, Ture or False 반환)
                    post.hashtags.add(hashtag)
            return redirect("posts:index")
    else:
        form = PostForm()
    context = {
        'form': form
    }

    return render(request, 'posts/form.html', context)


def hashtags(request, id):
    hashtag = get_object_or_404(HashTag, id=id)

    posts = hashtag.tagged_post.all()
    context = {
        'posts': posts
    }
    return render(request, 'posts/index.html', context)


def like(request, id):
    user = request.user
    post = get_object_or_404(Post, id=id)
    if user in post.like_users.all():
        post.like_users.remove(user)
    else:
        post.like_users.add(user)

insta-clone/accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% block body %}
  <form action="" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit">
  </form>
{% endblock %}

insta-clone/accounts/templates/accounts/user_page.html
{% extends 'base.html' %}
{% block body %}
<h1>{{user.username}}님의 유저페이지긔</h1>
<h5>팔로워 : {{user_info.followers.all | length}}</h5>
<h5>팔로잉 : {{user_info.followings.all | length}}</h5>
{% if user.is_authenticated and user != user_info %}
<a href="{% url 'accounts:follow' user_info.id %}">팔로우</a>
{% endif %}
{% endblock %}

insta-clone/insta/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
  integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
  integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<body>
  {% comment %}
  {% if user.is_authenticated %}
  <p>{{ user.username }}</p>
  <a href="{% url 'accounts:logout' %}">로그아웃</a>
  {% else %}
  <a href="{% url 'accounts:signup' %}">회원가입</a>
  <a href="{% url 'accounts:login' %}">로그인</a>
  {% endif %}
  {% endcomment %}

  <nav class="navbar navbar-light bg-light">
    <a class="navbar-brand">Navbar</a>
    <form class="form-inline">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    {% if user.is_authenticated %}
    <div>
      <span>{{ user.username }}</span>
      <a href="{% url 'accounts:logout' %}">로그아웃</a>
    </div>
    {% else %}
    <div>
      <a href="{% url 'accounts:signup' %}">회원가입</a>
      <a href="{% url 'accounts:login' %}">로그인</a>
    </div>
    {% endif %}
  </nav>
  <div class="container">
    {% block body %}
    {% endblock %}
  </div>

</body>

</html>

insta-clone/posts/templates/posts/_post.html
{% load make_link %}

<div class="card col-6" style="width: 18rem;">
  <img src="{{post.image.url}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title"></h5>
    <p class="card-text">{{post|hashtag_link|safe}}</p>
    <a href="#" class="btn btn-primary">좋아요</a>
  </div>
</div>

insta-clone/posts/templates/posts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit">
</form>
{% endblock %}

insta-clone/posts/templates/posts/index.html
{% extends 'base.html' %}
{% block body %}
{% for post in posts %}
{% include 'posts/_post.html' %}
<!-- <h1>{{post.content}}</h1> -->
{% endfor %}
{% endblock %}